apiVersion: argoproj.io/v1alpha1  # <--- CHANGED
kind: Rollout                     # <--- CHANGED
metadata:
  name: app-prod
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        workload: production
      containers:
      - name: my-app
        image: my-app:latest
        ports:
        - containerPort: 80
  strategy:
    canary:                       # <--- NEW STRATEGY
      steps:
      - setWeight: 20             # 1. Send 20% traffic to new version
      - pause: { duration: 30s }  # 2. Wait 30s (Jenkins checks health here)
      - setWeight: 100            # 3. Promote to 100%
